version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    image: manjiltamang/np-goverment-api-server:v1
    restart: always
    env_file:
      - .env
    environment:
      - PORT=3005
    ports:
      - "3005:3005"

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile.prod
    image: manjiltamang/np-goverment-dashboard:v1
    restart: always
    env_file:
      - .env
    environment:
      - PORT=3006
    ports:
      - "3006:3006"
