export enum ROLES {
  admin = "ROLE_ADMIN",
  ecStaff = "ROLE_EC_STAFF",
  serviceCenterStaff = "ROLE_SERVICE_CENTER_STAFF",
  level1 = "ROLE_LEVEL_1",
}
export const REST_ROOM_TYPE = [
  "Advertising Agency",
  "Airlines / GSA",
  "Architecture / Interior Design Firm",
  "Audit Firms / Tax Consultant",
  "Automotive Sales, Support & Service",
  "Banks",
  "Banquet / Catering",
  "BP0 / Call Center / ITES",
  "Construction / Real Estate",
  "Consulting / Legal",
  "Consumer Products / FMCG",
  "Designing / Printing / Publishing",
  "Direct Sells / Marketing Service",
  "Distribution Companies / Wholesale",
  "Education- School &amp; Colleges",
  "Embassies / Foreign Consulate",
  "Engineering Firms",
  "Event Management",
  "Finance Companies",
  "Garments / Carpet Industries",
  "Hardware / Network Companies",
  "Hospital /  Clinic / Diagnostic Centre",
  "Hotels / Resorts / Restaurant",
  "Hydropower / Alternate Energy",
  "Immigration &amp; Education Consultancy",
  "Information / Computer / Technology",
  "Insurance Companies",
  "ISP",
  "Logistic / Counter / Air Express Companies",
  "Manpower Recruitment",
  "Manufacturing / Engineering",
  "Media / Publication ( Newspaper, Magazines)",
  "Multinational Companies",
  "NGO / INGO / Development Projects",
  "Other",
  "Pharmaceuticals / Healthcare",
  "Poultry / Dairy / Veterinary",
  "Research Firms",
  "Retail / Shops",
  "Security Service Company",
  "Software Companies",
  "Telecommunication",
  "Trading- Export / Import / Merchandising",
  "Training Institutes",
  "Travel Agents / Tour Operators",
];
