FROM node:12-alpine AS builder

WORKDIR '/app'

COPY ./package.json ./
COPY ./yarn.lock ./

RUN yarn install

COPY . .

RUN yarn build

# -----------------------------------

FROM node:12-alpine

WORKDIR '/app'

COPY --from=builder /app ./

EXPOSE 3005

CMD ["yarn", "start"]
